package profile

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// Save writes the profile to path as YAML.
func Save(p *Profile, path string) error {
	data, err := yaml.Marshal(p)
	if err != nil {
		return fmt.Errorf("marshal profile: %w", err)
	}
	header := "# Generated by etcd-synthetic-load plan.\n" +
		"# WARNING: applying this profile with `load` creates large volumes of\n" +
		"# Secrets/ConfigMaps to stress etcd. Lab/Test/Dev clusters only.\n" +
		"# See README.md before running `load` against any cluster.\n"
	if err := os.WriteFile(path, append([]byte(header), data...), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// Load reads a profile.yaml from disk.
func Load(path string) (*Profile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var p Profile
	if err := yaml.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return &p, nil
}
